#####################################################################################################################################
# embedding_size: 64
# n_ui_layers: [3,4]
# n_layers: 1

# learning_rate_scheduler: [0.96, 50]
# lambda_coeff: 0.9
# reg_weight: [1e-5,1e-4]
# learning_rate: 0.001

# # cl_loss: 0.01 
# cl_loss1: [0.001,0.01,0.1]
# cl_loss2: [0.001,0.01,0.1]
# cl_loss3: [0.001, 0.01, 0.1]
# temperature: 0.2
# image_knn_k: [10,15,20,40]
# text_knn_k: [10,15,20,40]

# dropout_rate : [0, 0.1]

# MMWA: True
# MMWI: False
# MMCL: False

# hyper_parameters: ["n_ui_layers", "image_knn_k", "text_knn_k", "reg_weight", "dropout_rate", "cl_loss1","cl_loss2", "cl_loss3"]
#####################################################################################################################################


#########################################################Baby#####################################################
# embedding_size: 64
# # n_ui_layers: [1,2,3,4,5] #4
# n_ui_layers: 4 #4
# n_layers: 1

# learning_rate_scheduler: [0.96, 50]
# lambda_coeff: 0.9
# reg_weight: 1e-5
# learning_rate: 0.001

# cl_loss1: 0.01
# cl_loss2: 0.001
# # cl_loss3: 0.001
# # cl_loss1: [0.001,0.01,0.1]
# # cl_loss2: [0.001,0.01,0.1]
# # cl_loss3: [0.001, 0.01, 0.1] 
# # temperature: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9] # 0.2
# temperature: 0.3
# image_knn_k: 20
# text_knn_k: 15
# # image_knn_k: [5,10,15]
# # text_knn_k: [5,10,15]
# # image_knn_k: [10,15,20,25]
# # text_knn_k: [10,15,20,25]
# dropout_rate : 0
# MMWA: True
# MMWI: True
# MMCL: True
# # # # hyper_parameters: ["n_ui_layers", "image_knn_k", "text_knn_k", "reg_weight", "dropout_rate"]
# # # # hyper_parameters: ["cl_loss1", "cl_loss2", "cl_loss3"]
# # # hyper_parameters: ["cl_loss1", "cl_loss2"]
# # hyper_parameters: ["image_knn_k", "text_knn_k"]
# hyper_parameters: ["n_ui_layers"]
# hyper_parameters: ["temperature"]

# #########################################################Sports#####################################################
embedding_size: 64
# n_ui_layers: [1,2,3,4,5] # 3
n_ui_layers: 3
n_layers: 1

learning_rate_scheduler: [0.96, 50]
lambda_coeff: 0.9
reg_weight: 1e-4
learning_rate: 0.001

cl_loss1: 0.01
cl_loss2: 0.001
# cl_loss3: 0.01
# cl_loss1: [0.001,0.01,0.1]
# cl_loss2: [0.001,0.01,0.1] 
# image_knn_k: [10,15,20,25]
# text_knn_k: [10,15,20,25]
# temperature: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9] # 0.2
temperature: 0.1
image_knn_k: 15
text_knn_k: 10

# image_knn_k: [5,10,15]
# text_knn_k: [5,10,15]

dropout_rate : 0
MMWA: True
MMWI: True
MMCL: False

# # # hyper_parameters: ["n_ui_layers", "image_knn_k", "text_knn_k", "reg_weight", "dropout_rate"]
# # # hyper_parameters: ["cl_loss1", "cl_loss2", "cl_loss3"]
# hyper_parameters: ["image_knn_k", "text_knn_k"]
# # hyper_parameters: ["cl_loss1", "cl_loss2"]
# hyper_parameters: ["n_ui_layers"]
# hyper_parameters: ["temperature"]
#########################################################Clothing#####################################################
# embedding_size: 64
# # n_ui_layers: [1,2,4,5] # 3
# n_ui_layers: 3
# n_layers: 1

# learning_rate_scheduler: [0.96, 50]
# lambda_coeff: 0.9
# reg_weight: 1e-5
# learning_rate: 0.001

# cl_loss1: 0.01
# cl_loss2: 0.001
# # cl_loss3: 0.001
# # cl_loss1: [0.001,0.01,0.1]
# # cl_loss2: [0.001,0.01,0.1]
# # cl_loss3: [0.001, 0.01, 0.1] 
# # temperature: [0.1, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9] # 0.2
# temperature: 0.2

# image_knn_k: 25
# text_knn_k: 10
# # image_knn_k: [25, 20, 15, 10]
# # text_knn_k: [25, 20, 15, 10]

# dropout_rate : 0
# MMWA: True
# MMWI: True
# MMCL: True
# # hyper_parameters: ["n_ui_layers"]
# hyper_parameters: ["temperature"]
# # # hyper_parameters: ["n_ui_layers", "image_knn_k", "text_knn_k", "reg_weight", "dropout_rate"]
# # #hyper_parameters: ["cl_loss1", "cl_loss2", "cl_loss3"]
# hyper_parameters: ["image_knn_k", "text_knn_k"]
# hyper_parameters: ["cl_loss1", "cl_loss2"]